version: '3.8'

services:
  # ===================================
  # PostgreSQL Database (Development)
  # ===================================
  postgres:
    image: postgres:16-alpine
    container_name: brk-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-brk_competition_dev}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - brk-dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres} -d ${DB_DATABASE:-brk_competition_dev}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # ===================================
  # Redis Cache (Development)
  # ===================================
  redis:
    image: redis:7-alpine
    container_name: brk-redis-dev
    restart: unless-stopped
    command: >
      redis-server 
      --requirepass ${REDIS_PASSWORD:-redis_password}
      --appendonly no
      --save ""
    volumes:
      - redis_dev_data:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - brk-dev-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

# ===================================
# Development Volumes
# ===================================
volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local

# ===================================
# Development Network
# ===================================
networks:
  brk-dev-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16 